[theme]
base = "light"
primaryColor = "#4338ca"
backgroundColor = "#f4f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#111827"
font = "sans serif"

[client]
showErrorDetails = true

[server]
enableCORS = true

