[theme]
base = "light"
primaryColor = "#F97316"              # オレンジ
backgroundColor = "#F7F5F2"
secondaryBackgroundColor = "#FFF6EF"  # うっすらオレンジ
textColor = "#1F2937"                 # ダークグレー
font = "sans serif"

[client]
showErrorDetails = true

[server]
enableCORS = true
